/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_internal_ScanWork */

#ifndef _Included_com_hd_internal_ScanWork
#define _Included_com_hd_internal_ScanWork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_create
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_ScanWork_sj_1create
  (JNIEnv *, jclass, jstring, jint, jstring, jint);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_cancel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1cancel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_check_devices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1check_1devices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_scan_photo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1scan_1photo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_scan_point
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1scan_1point
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_config
 * Signature: (JIDDFDDD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1config
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jfloat, jdouble, jdouble, jdouble);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_set_data_dir
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1set_1data_1dir
  (JNIEnv *, jclass, jlong, jstring, jstring,jstring);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_state
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1get_1state
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_angle
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_ScanWork_sj_1get_1angle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_temperature
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_ScanWork_sj_1get_1temperature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_tilt
 * Signature: (J[D)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1get_1tilt
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_battery
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_ScanWork_sj_1get_1battery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_led
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1led
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_search_zero
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_ScanWork_sj_1search_1zero
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_ScanWork
 * Method:    sj_get_info
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hd_internal_ScanWork_sj_1get_1info
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
