/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_internal_WebServer */

#ifndef _Included_com_hd_internal_WebServer
#define _Included_com_hd_internal_WebServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_internal_WebServer
 * Method:    start_webserver
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_WebServer_start_1webserver
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hd_internal_WebServer
 * Method:    stop_webserver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_WebServer_stop_1webserver
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
