/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_unittest_UnitTest */

#ifndef _Included_com_hd_unittest_UnitTest
#define _Included_com_hd_unittest_UnitTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_unittest_UnitTest
 * Method:    native_main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hd_unittest_UnitTest_native_1main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
