/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_internal_Control */

#ifndef _Included_com_hd_internal_Control
#define _Included_com_hd_internal_Control
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_internal_Control
 * Method:    hl_Constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_Control_hl_1Constructor
  (JNIEnv *, jclass);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_Destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hd_internal_Control_hl_1Destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_open
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1open
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_open_socket
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1open_1socket
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_prepare
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1prepare
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1stop
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_get_angle
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_Control_hl_1turntable_1get_1angle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_config
 * Signature: (JIDD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1config
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_turn
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1turn
  (JNIEnv *, jclass, jlong, jdouble);


/*
 * Class:     com_hd_internal_Control
 * Method:    hl_turntable_turn
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1turntable_1check
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_camera_take_photo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1camera_1take_1photo
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_hd_internal_Control
 * Method:    hl_get_temperature
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_Control_hl_1get_1temperature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_get_tilt
 * Signature: (J)F
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1get_1tilt
(JNIEnv *env, jclass clazz, jlong priv,jdoubleArray jda);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_get_battery
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_hd_internal_Control_hl_1get_1battery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_led_Red
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1led_1red
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_led_greed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1led_1green
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_led_off
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1led_1off
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_search_zero
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Control_hl_1search_1zero
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Control
 * Method:    hl_get_info
 * Signature: (JILjava/lang/String;I)I
 */
JNIEXPORT jstring JNICALL Java_com_hd_internal_Control_hl_1get_1info
  (JNIEnv *, jclass, jlong, jint,jint);

#ifdef __cplusplus
}
#endif
#endif
