/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hd_internal_WebServer.h"
#include <server/hd_websocket.h>
/*
 * Class:     com_hd_internal_WebServer
 * Method:    start_webserver
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_WebServer_start_1webserver
(JNIEnv *env, jclass thiz, jstring jsroot)
{
	int ret;
	char *root,buf[1024];
	root = (*env)->GetStringUTFChars(env, jsroot, 0);
	DMSG((STDOUT,"Start Web Server root@%s",root));

	sprintf(buf,"%s/html",root);
	ret = webhttp_start(buf);

	sprintf(buf,"%s/html/websocket",root);
	ret = websocket_start(buf);

	(*env)->ReleaseStringUTFChars(env, jsroot, root);

	return ret;
}

/*
 * Class:     com_hd_internal_WebServer
 * Method:    stop_webserver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_WebServer_stop_1webserver
(JNIEnv *env, jclass thiz)
{
	 return websocket_stop();
}

